name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build binary
        run: |
          mkdir -p dist
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/stepwise-${{ matrix.goos }}-${{ matrix.goarch }}$ext ./cmd/stepwise/main.go
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stepwise-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/stepwise-*

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save changelog
        run: echo "${{ steps.changelog.outputs.changelog }}" > changelog.md
      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.md

  release:
    name: Create GitHub Release
    needs: [build, changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Find changelog
        run: |
          find dist -name changelog.md
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: dist/changelog/changelog.md
          files: dist/**/stepwise-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 